package mihon.core.migration.migrations

import mihon.core.migration.Migration

val migrations: List<Migration>
    get() = listOf(
        SetupBackupCreateMigration(),
        SetupLibraryUpdateMigration(),
        SetupEHentaiUpdateMigration(),
        SetupSyncDataMigration(),
        // DelegateNHentaiMigration(),
        // MergedMangaRewriteMigration(),
        // LogoutFromMALMigration(),
        // MoveDOHSettingMigration(),
        // ResetRotationSettingMigration(),
        // ResetReaderSettingsMigration(),
        // DeleteOldMangaDexTracksMigration(),
        // RemoveOldReaderThemeMigration(),
        // RemoveShorterLibraryUpdatesMigration(),
        // MoveLibrarySortingSettingsMigration(),
        // RemoveShortLibraryUpdatesMigration(),
        // MoveLibraryNonCompleteSettingMigration(),
        // DeleteOldEhFavoritesDatabaseMigration(),
        // MoveSecureScreenSettingMigration(),
        // ChangeMiuiExtensionInstallerMigration(),
        // MoveCoverOnlyGridSettingMigration(),
        // MoveCatalogueCoverOnlyGridSettingMigration(),
        // MoveLatestToFeedMigration(),
        // MoveReaderTapSettingMigration(),
        // MoveSortingModeSettingsMigration(),
        // MoveSortingModeSettingMigration(),
        // AlwaysBackupMigration(),
        // ResetFilterAndSortSettingsMigration(),
        // ChangeThemeModeToUppercaseMigration(),
        // MoveReadingButtonSettingMigration(),
        // ChangeTrackingQueueTypeMigration(),
        // LogoutFromMangaDexMigration(),
        // RemoveUpdateCheckerJobsMigration(),
        // RemoveBatteryNotLowRestrictionMigration(),
        // MoveRelativeTimeSettingMigration(),
        // ClearBrokenPagePreviewCacheMigration(),
        // MoveSettingsToPrivateOrAppStateMigration(),
        // MoveExtensionRepoSettingsMigration(),
        // MoveCacheToDiskSettingMigration(),
        // MoveEncryptionSettingsToAppStateMigration(),
        // Yomiku (Badley08) -->
        IntegratedHentaiMigration(),
        SetupAppUpdateMigration(),
        EHentaiMigration(),
        MergedMangaDedupeModeMigration(),
        // Yomiku (Badley08) <--
        TrustExtensionRepositoryMigration(),
        CategoryPreferencesCleanupMigration(),
        RemoveDuplicateReaderPreferenceMigration(),
        // Yomiku (Badley08) -->
        DisabledRepoMigration(),
        SyncPrefKeyMigration(),
        ChapterUrlHashMigration(),
        BuiltinExtensionStoreMigration(),
        // Yomiku (Badley08) <--
    )
